### ISSUE TITLE
Trackpoint please, please *please*

### ISSUE THREAD

**Issue by chx** [FrameworkComputer/InputModules#1]
The IBM patents have expired... https://patents.google.com/patent/US6115030A/en

I am sure https://tex.com.tw/ have the modules for an agreeable price.

**Comment by jyancat** [comment]
Issues are not for feature requests, this is generally for reporting issues with anything in this repository. If you want to request a feature/new module you can use the forums [https://community.frame.work/](url)

**Comment by eclecticc** [comment]
@jyancat 's comment is correct.  Closing out.

**Comment by chx** [comment]
Extremely disappointing.

**Comment by eclecticc** [comment]
To be clear, @jyancat 's correct comment is that GitHub Issues are for reporting bugs or adding enhancements within the code or CAD that exists in the repository.  Feature requests for the product itself go in the Framework Community.

**Comment by cscott** [comment]
See https://community.frame.work/t/thinkpad-keyboard-mod-super-early-stages/38484 for active discussion.
